# Generated by Django 3.2.8 on 2021-10-28 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0020_auto_20211026_2316'),
        ('config', '0002_webhook_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.webhook')),
                ('webhook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.listing')),
            ],
        ),
    ]
