# Generated by Django 3.0.5 on 2020-06-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='contact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='rent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='title',
            field=models.CharField(max_length=244, null=True),
        ),
    ]
