# Generated by Django 3.0.7 on 2020-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20200605_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='scraped',
        ),
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.SmallIntegerField(null=True),
        ),
    ]
