# Generated by Django 3.0.7 on 2020-06-12 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20200610_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
