# Generated by Django 3.0.8 on 2020-07-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='post_container_selector',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='post_link_list_selector',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_selector',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='limit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rent_selector',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title_selector',
            field=models.CharField(default='', max_length=255),
        ),
    ]
