# Generated by Django 3.0.8 on 2020-07-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20200708_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
