# Generated by Django 3.0.8 on 2020-07-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20200708_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
