# Generated by Django 3.0.8 on 2020-07-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20200710_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='contact_selector',
            new_name='selector',
        ),
        migrations.AddField(
            model_name='parameter',
            name='value',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
