# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-12 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20201005_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='url',
            field=models.CharField(max_length=400),
        ),
    ]
