# Generated by Django 3.0.8 on 2020-07-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20200711_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Apartment')),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Parameter')),
            ],
        ),
    ]
