# Generated by Django 3.1.2 on 2021-04-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_auto_20201013_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.CharField(max_length=2000),
        ),
    ]
