# Generated by Django 3.1.2 on 2021-10-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_auto_20210414_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=400)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.apartment')),
            ],
        ),
    ]
