# Generated by Django 3.0.8 on 2020-07-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_auto_20200711_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='desc_selector',
            field=models.CharField(default='', max_length=255),
        ),
    ]
