# Generated by Django 3.1.2 on 2021-10-20 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.apartment'),
        ),
    ]
