# Generated by Django 3.1.2 on 2021-10-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_auto_20211020_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='picture_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
