# Generated by Django 3.1.2 on 2021-10-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_auto_20211020_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='picture_url',
        ),
    ]
