# Generated by Django 3.1.2 on 2021-10-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_remove_apartment_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='square',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='square_selector',
            field=models.CharField(default='', max_length=255),
        ),
    ]
