# Generated by Django 3.1.2 on 2021-10-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_auto_20211022_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='square_selector',
            new_name='description_2_selector',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='square',
        ),
        migrations.AddField(
            model_name='apartment',
            name='description_2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='subtitle',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='subtitle_selector',
            field=models.CharField(default='', max_length=255),
        ),
    ]
