# Generated by Django 3.1.2 on 2021-10-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0018_auto_20211022_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='contact_selector',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description_2_selector',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description_selector',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture_selector',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='post_container_selector',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='post_link_list_selector',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rent_selector',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='subtitle_selector',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title_selector',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
