# Generated by Django 3.2.8 on 2021-10-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_auto_20211022_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='description_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='subtitle',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
