# Generated by Django 3.2.8 on 2021-10-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0020_auto_20211026_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
